trainingInput:
    hyperparameters:
      goal: MAXIMIZE
      maxTrials: 32
      maxParallelTrials: 8
      hyperparameterMetricTag: accuracy
      enableTrialEarlyStopping: FALSE 
      params:
      - parameterName: numberestimators
        type: DISCRETE
        discreteValues: [
            10, 
            20, 
            30, 
            40, 
            50,
            100,
            150,
            200
            ]
      - parameterName: minsamplesleaf
        type: DISCRETE
        discreteValues: [
            1, 
            2, 
            4, 
            6, 
            8,
            10,
            12
            ]